fix(CI/CD) delete a rule of the ci/cd

diff --git a/.github/workflows/epi.yml b/.github/workflows/epi.yml
--- a/.github/workflows/epi.yml
+++ b/.github/workflows/epi.yml
@@ -1,43 +1,38 @@
 name: epici
 run-name: epici
 on:
-    pull_request:
-        branches-ignore:
-            - 'mirror/**'
-            - 'ga-ignore-**'
     push:
-        branches-ignore:
-            - 'mirror/**'
-            - 'ga-ignore-**'
+        branches: [ main]
+
 env:
-    MIRROR_URL: "https://github.com/EpitechPGE3-2026/G-SVR-500-REN-5-1-survivor-4"
+    MIRROR_URL: "git@github.com:EpitechPGE3-2026/G-SVR-500-REN-5-1-survivor-4.git"
     EXECUTABLES: ${{vars.GIT_BINARIES}}
     GH_PUB_KEY:
       github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
 jobs:
-    check_program_compilation:
-        name: check_program_compilation
-        runs-on: ubuntu-latest
-        container:
-            image: epitechcontent/epitest-docker
-        steps:
-            - uses: actions/checkout@v3
-            - id: check_program_compilation
-              run: make
-              timeout-minutes: 2
-            - run: make clean
-            - run: |
-                OIFS=$IFS
-                IFS=','
-                for x in $EXECUTABLES; do
-                    if [ ! -x "./$x" ]; then
-                        echo "Error: Executable ./$x not found or not executable."
-                        exit 1
-                    fi
-                done
-                IFS=$OIFS
+    #check_program_compilation:
+#        name: check_program_compilation
+#        runs-on: ubuntu-latest
+#       container:
+#            image: epitechcontent/epitest-docker
+#        steps:
+#            - uses: actions/checkout@v3
+#            - id: check_program_compilation
+#              run: make
+#              timeout-minutes: 2
+#            - run: make clean
+#            - run: |
+#                OIFS=$IFS
+#                IFS=','
+#                for x in $EXECUTABLES; do
+#                    if [ ! -x "./$x" ]; then
+#                        echo "Error: Executable ./$x not found or not executable."
+#                        exit 1
+#                    fi
+#                done
+#               IFS=$OIFS
     push_repository:
-        needs: check_program_compilation
+#        needs: check_program_compilation
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
@@ -55,7 +50,7 @@ jobs:
               run: |
                   git config --global user.email "titouan.hochet@epitech.eu"
                   git config --global user.name "titouanhct"
-                  git remote add target https://github.com/EpitechPGE3-2026/G-SVR-500-REN-5-1-survivor-4
+                  git remote add target git@github.com:EpitechPGE3-2026/G-SVR-500-REN-5-1-survivor-4.git
             - name: Push to mirror
               run: |
                   git checkout -b main || git checkout main
